// Mock filter options - realistic volume for prototyping the faceted search UI
// These will be replaced with API calls to the canonical database later

export const INDUSTRIES = [
  "SaaS",
  "Fintech",
  "Financial Services",
  "Healthcare",
  "HealthTech",
  "E-commerce",
  "Retail",
  "Manufacturing",
  "Industrial",
  "Legal Tech",
  "Legal Services",
  "EdTech",
  "Education",
  "Real Estate",
  "PropTech",
  "Construction",
  "Logistics",
  "Supply Chain",
  "Transportation",
  "Automotive",
  "Energy",
  "CleanTech",
  "Oil & Gas",
  "Telecommunications",
  "Media & Entertainment",
  "Advertising",
  "Marketing Tech",
  "HR Tech",
  "Recruiting",
  "Insurance",
  "InsurTech",
  "Banking",
  "Investment Management",
  "Private Equity",
  "Venture Capital",
  "Consulting",
  "Professional Services",
  "Cybersecurity",
  "IT Services",
  "Cloud Infrastructure",
  "Data & Analytics",
  "AI & Machine Learning",
  "Robotics",
  "IoT",
  "Blockchain",
  "Gaming",
  "Sports Tech",
  "Food & Beverage",
  "FoodTech",
  "Agriculture",
  "AgTech",
  "Biotech",
  "Pharmaceuticals",
  "Medical Devices",
  "Travel & Hospitality",
  "Aerospace",
  "Defense",
  "Government",
  "Nonprofit",
  "Consumer Goods",
  "Fashion & Apparel",
  "Beauty & Wellness",
  "Fitness",
  "Home Services",
  "Marketplace",
  "Social Media",
  "Developer Tools",
  "API Infrastructure",
];

export const COMPANY_SIZES = [
  "1-10",
  "11-50",
  "51-200",
  "201-500",
  "501-1000",
  "1001-5000",
  "5001-10000",
  "10000+",
];

export const TAGS = [
  "decision-maker",
  "technical",
  "founder",
  "co-founder",
  "c-suite",
  "vp-level",
  "director-level",
  "manager",
  "individual-contributor",
  "marketing",
  "sales",
  "engineering",
  "product",
  "operations",
  "finance",
  "hr",
  "legal",
  "it",
  "customer-success",
  "enterprise",
  "mid-market",
  "smb",
  "startup",
  "high-value",
  "agency-lead",
  "investor",
  "advisor",
  "board-member",
  "series-a",
  "series-b",
  "series-c",
  "bootstrapped",
  "profitable",
  "hypergrowth",
  "public-company",
  "recently-funded",
  "hiring",
  "expanding",
  "remote-first",
  "tech-forward",
  "legacy-systems",
  "digital-transformation",
  "early-adopter",
  "budget-holder",
  "influencer",
  "champion",
  "blocker",
  "warm-intro",
  "cold-outreach",
  "conference-met",
  "webinar-attendee",
  "content-engaged",
  "website-visitor",
  "trial-user",
  "churned",
  "competitor-user",
];

export const JOB_TITLES = [
  "CEO",
  "CTO",
  "CFO",
  "COO",
  "CMO",
  "CRO",
  "CIO",
  "CISO",
  "CPO",
  "VP of Engineering",
  "VP of Sales",
  "VP of Marketing",
  "VP of Product",
  "VP of Operations",
  "VP of Finance",
  "VP of HR",
  "VP of Customer Success",
  "Director of Engineering",
  "Director of Sales",
  "Director of Marketing",
  "Director of Product",
  "Director of Operations",
  "Engineering Manager",
  "Sales Manager",
  "Marketing Manager",
  "Product Manager",
  "Project Manager",
  "Account Executive",
  "Account Manager",
  "Business Development Rep",
  "Sales Development Rep",
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Engineer",
  "Principal Engineer",
  "Data Scientist",
  "Data Engineer",
  "DevOps Engineer",
  "Solutions Architect",
  "Technical Architect",
  "UX Designer",
  "Product Designer",
  "Growth Manager",
  "Demand Gen Manager",
  "Content Manager",
  "HR Manager",
  "Talent Acquisition",
  "Recruiter",
  "Finance Manager",
  "Controller",
  "General Counsel",
  "Head of Legal",
  "Founder",
  "Co-Founder",
  "Partner",
  "Managing Director",
  "Board Member",
  "Advisor",
  "Consultant",
];

export const LOCATIONS = [
  "San Francisco, CA",
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Boston, MA",
  "Seattle, WA",
  "Austin, TX",
  "Denver, CO",
  "Miami, FL",
  "Atlanta, GA",
  "Dallas, TX",
  "Houston, TX",
  "Phoenix, AZ",
  "San Diego, CA",
  "Portland, OR",
  "Salt Lake City, UT",
  "Nashville, TN",
  "Charlotte, NC",
  "Minneapolis, MN",
  "Detroit, MI",
  "Philadelphia, PA",
  "Washington, DC",
  "Raleigh, NC",
  "San Jose, CA",
  "Oakland, CA",
  "London, UK",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Berlin, Germany",
  "Paris, France",
  "Amsterdam, Netherlands",
  "Dublin, Ireland",
  "Singapore",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Tel Aviv, Israel",
  "Bangalore, India",
  "Remote",
];

// Helper to search/filter options
export function searchOptions(options: string[], query: string): string[] {
  if (!query.trim()) return options.slice(0, 10); // Show first 10 when no query
  const q = query.toLowerCase();
  return options.filter((opt) => opt.toLowerCase().includes(q));
}

